# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkJnN6-_TQFJRB-gzgXXVa6x2FlgSRI7
"""

import pandas as pd

import numpy as np
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

movies



# Merge the datasets on the 'movieId'
data = pd.merge(ratings, movies, on='movieId')

# Create a user-item matrix
user_item_matrix = data.pivot_table(index='userId', columns='title', values='rating')

# Fill NaN values with 0 (or use another method to handle missing values)
user_item_matrix = user_item_matrix.fillna(0)

user_item_matrix = data.pivot_table(index='userId', columns='title', values='rating')
user_item_matrix = user_item_matrix.fillna(0)

# Transpose the matrix for KNN
matrix_transposed = user_item_matrix.T

# Fit the KNN model
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(matrix_transposed)

# Function to get movie recommendations
def get_movie_recommendations(movie_name, n_recommendations):
    distances, indices = knn.kneighbors(matrix_transposed.loc[movie_name].values.reshape(1, -1), n_neighbors=n_recommendations+1)
    recommended_movies = [matrix_transposed.index[i] for i in indices.flatten()][1:]
    return recommended_movies

# Example: Get 5 movie recommendations for a specific movie
movie_name = 'Toy Story (1995)'
recommendations = get_movie_recommendations(movie_name, 10)
print(f"Recommendations for {movie_name}:")
for i, movie in enumerate(recommendations, 1):
    print(f"{i}. {movie}")